# Generated by Django 2.1.12 on 2019-09-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190919_1819'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_info_login',
        ),
    ]
