# Generated by Django 2.1.12 on 2019-10-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190926_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
